<?php
/* @var \Magento\Framework\View\Element\Template $block */
?>

<ul>
    <li class="quotation">
        <a href="#">
            <span>
                <i class="fas fa-pen-square"></i>
                <?php echo __('Request a Quote'); ?>
            </span>
        </a>
    </li>
    <li class="skype">
        <a href="skype:mudasser.hayat1?chat">
            <span>
                <i class="fab fa-skype"></i>
                <?php echo __('skype : mudasser.hayat1'); ?>
            </span>
        </a>
    </li>
</ul>
